### PR TITLE
#52 - Refactor unit test layout and naming to be more BDD orientated

### PR DESCRIPTION
**Pull request by AwaNoodle**
Moved invalid request data tests over to using parameterised tests

### CODE REVIEW

**Comment by AwaNoodle** [comment]
current

This is the output via ReSharper with the tests as in the pull request. They're showing as the same test, as they are, but with the different parameters to show whats being tested. 

changednames

It is possible to attach a name to the test data to change the output. This still keeps the benefit of having the test stay as one piece of code but showing whats being tested.

**Comment by lholman** [comment]
Great, if we can make them nice meaningful names lets go for it. I see there are 6 in the second screen shot, lets keep the initial pull request to those first three and get everything right.

**Comment by lholman** [comment]
One thing I wanted you to check is the TestResult.xml that is generated by the build script in the root folder, see how that reports the parameterised tests.  That's what TeamCity uses to report on test execution.

**Comment by AwaNoodle** [comment]
updatedtestcasenames

Modifiying the test name will look like the above.

I'll look at the output XML shortly.

**Comment by AwaNoodle** [comment]
This is the output in the TestResult.xml. The tests are nicely split down by name space, then as a parametrized test, and then with the specified names from the test case.

``` xml
<test-suite type="ParameterizedTest" name="GivenRequestWithInvalidData_ThenAppropriateHttpCodeAndErrorAreReturned" executed="True" result="Success" success="True" time="0.008" asserts="0">
    <results>
        <test-case name="Femah.Core.Tests.WhenProcessingPutRequests.GivenRequestWithInvalidJson_ThenHttpCode400AndErrorAreReturned" executed="True" result="Success" success="True" time="0.001" asserts="0" />
        <test-case name="Femah.Core.Tests.WhenProcessingPutRequests.GivenRequestWithInvalidEnabledValue_ThenHttpCode400AndErrorAreReturned" executed="True" result="Success" success="True" time="0.004" asserts="0" />
        <test-case name="Femah.Core.Tests.WhenProcessingPutRequests.GivenRequestWithInvalidFeatureType_ThenHttpCode400AndErrorAreReturned" executed="True" result="Success" success="True" time="0.000" asserts="0" />
    </results>
</test-suite>
```

**Comment by lholman** [comment]
Seems spot on. Can you update a pull request with subsequent commits?

-----Original Message-----

**Comment by AwaNoodle** [comment]
Should be in the request now.

**Pull request merged**
