### PR TITLE
#99 - Add unit tests for the Femah.Core.Providers.SqlServerProvider

### PR DESCRIPTION
**Pull request by AwaNoodle**
Added unit test for deleting old feature switches on initialize of the SQL Provider.

Atm there are a lot of mocks in there. I think these will be removed in my next test and I'll write a general purpose sql provider mock.

### CODE REVIEW

**Comment by AwaNoodle** [comment]
Added a refactor for the amount of mocks being used. It's now wrapped up in a fake. All current tests have been adjusted to use it.

**Comment by lholman** [comment]
Hey buddy, not ignoring you. Just settling in to the new role and I haven't got a Windows environment on a laptop to use during the commute at the moment. @hotstone could you review, failing that I'll pick them up nearer the weekend.

**Comment by AwaNoodle** [comment]
@hotstone - had a chance to look over my PRs?

**Comment by lholman** [comment]
@hotstone Could you take a look and merge in the good way https://github.com/lloydstone/femah/issues/65 pleasey ?

**Comment by hotstone** [comment]
Done.

**Pull request closed without merging**
